#!/bin/bash

# The normal expectation is that all of this is installed in
#          /FPT   
# If not, you will have to edit this script to reflect where
# you really installed it.


clist=""

for name in $@; do

  bname=" $name"
  clist=("$clist""$bname")

done

#echo $clist

cc -I/usr/X11/include  -I/FPT/Source -I/FPT/HeadersC /FPT/DotosC/*.o    $clist   -L/usr/X11/lib -lm -lX11 -lXext