#!/bin/bash

clist=""

for name in $@; do

  bname=" $name"
  clist=("$clist""$bname")

done

#echo $clist

cc -I/usr/X11/include -I/opt/X11/include  -I$prefix/Source -I$prefix/HeadersC $prefix/DotosC/*.o    $clist   -L/opt/X11/lib -L/usr/X11/lib -lm -lX11 -lXext
